#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

# Backward compatibility:
#   build.sh init
#   build.sh router
# Explicit platform form:
#   build.sh debian router
#   build.sh alpine router
if [ "$#" -eq 1 ]; then
    PLATFORM=debian
    PRODUCT="$1"
elif [ "$#" -eq 2 ]; then
    PLATFORM="$1"
    PRODUCT="$2"
else
    printf 'Usage: %s [debian|alpine] <product>\n' "$0" >&2
    exit 2
fi

case "$PLATFORM" in
    debian)
        PLATFORM_LABEL="Debian 13"
        OUTPUT_PREFIX="debian13"
        ;;
    alpine)
        PLATFORM_LABEL="Alpine Linux"
        OUTPUT_PREFIX="alpine"
        ;;
    *)
        printf 'ERROR Unsupported platform: %s\n' "$PLATFORM" >&2
        exit 2
        ;;
esac

for value in "$PLATFORM" "$PRODUCT"; do
    [[ "$value" =~ ^[a-z0-9][a-z0-9-]*$ ]] || {
        printf 'ERROR Invalid build name: %s\n' "$value" >&2
        exit 2
    }
done

BUILD_FILE="$ROOT_DIR/$PLATFORM/build/$PRODUCT.sh"
OUTPUT="$ROOT_DIR/dist/$OUTPUT_PREFIX-$PRODUCT.sh"

[ -r "$BUILD_FILE" ] || {
    printf 'ERROR Build definition not found: %s\n' "$BUILD_FILE" >&2
    exit 1
}

# shellcheck source=/dev/null
source "$BUILD_FILE"

declare -p MODULES >/dev/null 2>&1 || {
    printf 'ERROR Build definition does not declare MODULES.\n' >&2
    exit 1
}

mkdir -p "$ROOT_DIR/dist"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
    cat <<EOF
#!/usr/bin/env bash
# Generated by HostKit. Do not edit manually.
# Product: ${PRODUCT^^}
# Platform: $PLATFORM_LABEL

set -Eeuo pipefail

EOF

    for module in "${MODULES[@]}"; do
        [[ "$module" =~ ^[a-z0-9][a-z0-9-]*$ ]] || {
            printf 'ERROR Invalid module name: %s\n' "$module" >&2
            exit 1
        }
        module_file="$ROOT_DIR/$PLATFORM/modules/$module.sh"
        [ -r "$module_file" ] || {
            printf 'ERROR Module not found: %s\n' "$module_file" >&2
            exit 1
        }
        printf '# ---- module: %s ----\n' "$module"
        cat "$module_file"
        printf '\n'
    done

    printf '# ---- product: %s ----\n' "$PRODUCT"
    cat "$BUILD_FILE"
    printf '\nhostkit_main "$@"\n'
} >"$tmp"

bash -n "$tmp"
install -m 0755 "$tmp" "$OUTPUT"
printf 'OK Built %s\n' "$OUTPUT"
