#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
PRODUCT="${1:-}"

if [ -z "$PRODUCT" ]; then
    printf 'Usage: %s <product>\n' "$0" >&2
    exit 2
fi

if [[ ! "$PRODUCT" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
    printf 'ERROR Invalid product name: %s\n' "$PRODUCT" >&2
    exit 2
fi

BUILD_FILE="$ROOT_DIR/debian/build/$PRODUCT.sh"
OUTPUT="$ROOT_DIR/dist/debian13-$PRODUCT.sh"

if [ ! -r "$BUILD_FILE" ]; then
    printf 'ERROR Build definition not found: %s\n' "$BUILD_FILE" >&2
    exit 1
fi

# shellcheck source=/dev/null
source "$BUILD_FILE"

if ! declare -p MODULES >/dev/null 2>&1; then
    printf 'ERROR Build definition does not declare MODULES.\n' >&2
    exit 1
fi

mkdir -p "$ROOT_DIR/dist"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
    cat <<EOF
#!/usr/bin/env bash
# Generated by HostKit. Do not edit manually.
# Product: ${PRODUCT^^}
# Platform: Debian 13

set -Eeuo pipefail

EOF

    for module in "${MODULES[@]}"; do
        if [[ ! "$module" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
            printf 'ERROR Invalid module name: %s\n' "$module" >&2
            exit 1
        fi
        module_file="$ROOT_DIR/debian/modules/$module.sh"
        if [ ! -r "$module_file" ]; then
            printf 'ERROR Module not found: %s\n' "$module_file" >&2
            exit 1
        fi
        printf '# ---- module: %s ----\n' "$module"
        cat "$module_file"
        printf '\n'
    done

    printf '# ---- product: %s ----\n' "$PRODUCT"
    cat "$BUILD_FILE"
    printf '\nhostkit_main "$@"\n'
} >"$tmp"

bash -n "$tmp"
install -m 0755 "$tmp" "$OUTPUT"
printf 'OK Built %s\n' "$OUTPUT"
