#!/usr/bin/env bash
set -euo pipefail

# Build a single-file script: dist/hostkit-deb12-init.sh
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/dist/hostkit-deb12-init.sh"

mkdir -p "$ROOT/dist"

{
  # shebang + strict mode
  echo '#!/usr/bin/env bash'
  echo '# Hostkit (single-file build) — generated by tools/mkdist.sh'
  echo 'set -euo pipefail'
  echo

  # copy config block from scripts/deb12-init.sh
  awk '
    /##### === Configurable variables === #####/ {print; copy=1; next}
    copy==1 {print; if ($0 ~ /^##########################################$/) {copy=0; print "";}}
  ' "$ROOT/scripts/deb12-init.sh"

  # cat modules in a stable order
  for m in log.sh detect.sh apt.sh time.sh user_sudo.sh sshd.sh unattended.sh \
           fail2ban.sh firewall_iptables.sh sysctl.sh journal.sh services.sh; do
    echo "# === module: $m ==="
    # compatible shebang removal for macOS/Linux
    sed '1{/^#!.*$/d;}' "$ROOT/modules/$m"
    echo
  done

  # append main() from scripts/deb12-init.sh without sourcing lines
  awk '
    /main\(\)/,0 {print}
  ' "$ROOT/scripts/deb12-init.sh" | sed '/^\. "\$BASE_DIR\/modules\//d'
} > "$OUT"

chmod +x "$OUT"
echo "Built: $OUT"
